177 combined time entry description input
codelayerhq/likvi-timetracking-desktop pull request #213
Opened 2021-07-13 06:59 UTC by vivienhennig

2021-07-15 08:19 UTC, vivienhennig commented on src/components/ActionBar.vue
> +      // Todo: find way to differ between selected customer / project and task
Hier muss irgendwie unterschieden werden zwischen dem starten der Task oder dem auswählen von Customer oder Project. Habt ihr hier eine Idee?

2021-07-15 08:20 UTC, vivienhennig commented on src/components/NewTimeEntryInput.vue
>            // ToDo: using Popper.js in this way (destroying, creating) is not poptimal
Es funktioniert nun auch ohne Popper.js. Sollen wir das dann ohne Popper.js nutzen, oder spricht da etwas gegen?

2021-07-19 19:43 UTC, tobiasdierich commented
Auch der PR sollte einmal rebased werden auf dem aktuellen master, da der Commit "feat: autoselect customer when project is selected" hier nochmal mit drin ist.

2021-07-20 10:53 UTC, tobiasdierich requested changes
Wenn bei der Suche nach Projekt oder Kunde keine Ergebnisse vorhanden sind, zeigt das Dropdown "Keine Zeiteinträge gefunden" an. Den Text sollten wir noch anpassen, je nachdem wonach gerade gesucht wurde.

![Screenshot 2021-07-20 at 12 51 40](https://user-images.githubusercontent.com/20173900/126312213-c4672901-3229-4443-9142-d233fba5f7d8.png)

2021-07-20 10:53 UTC, tobiasdierich commented on src/components/NewTimeEntryInput.vue
> +            } = await new ProjectsService().suggest(text);
Hier müssen wir `.search(text)` verwenden wenn `text` gesetzt ist.

2021-07-20 10:53 UTC, tobiasdierich commented on src/components/NewTimeEntryInput.vue
> +            } = await new CustomersService().suggest(text);
Ebenso hier: wenn `text` gesetzt ist, ist `.search(text)` der richtige Call.

2021-07-20 11:03 UTC, tobiasdierich commented on src/components/NewTimeEntryInput.vue
> +          } else if (text.endsWith("#")) {
Wenn wir checken ob der input auf `#` endet, ist keine Suche nach Projekten möglich. Beispielsweise wenn ich in den Input `#Müller` eingebe, wird eine Suche nach Zeiteinträgen ausgelöst (da `text.endsWith("#") === false`), anstatt nach Projekten die mit "Müller" beginnen zu suchen. Ich denke eine gute Lösung wäre, zu prüfen, ob in `text` ein `#` oder ein `@` irgendwo vorkommt und falls beides vorkommt jeweils das zu nehmen welches weiter hinten steht. Also z. B. bei Eingabe `abc` wird nach Zeiteinträgen gesucht, bei `abc #` werden Projekte vorgeschlagen, bei `abc #projekt @` werden Kunden vorgeschlagen.

2021-07-20 11:03 UTC, tobiasdierich commented on src/components/NewTimeEntryInput.vue
> +          if (item.value?.description) {
@a47ae Kann man prüfen welchen Typ `item` tatsächlich hat? AutocompleteItem ist ja ein Partial aus den 3 verschiedenen Optionen.

2021-07-21 08:17 UTC, a47ae commented on src/components/NewTimeEntryInput.vue
> +          if (item.value?.description) {
Nein, die Typen sind ja nicht zu runtime verfügbar, man müsste also noch ein `type` Feld hinzufügen, dass den Typ enthält.

2021-07-21 08:59 UTC, a47ae requested changes

2021-07-21 08:59 UTC, a47ae commented on src/components/NewTimeEntryInput.vue
> +    window.addEventListener("keydown", function (event: KeyboardEvent) {
Der Teil ist glaube ich noch vom Debugging übrig

2021-07-21 08:59 UTC, a47ae commented on src/components/Tag.vue
> +      emit("removeTag", props.index);
Hier würde ich nicht den index als Prop übergeben, sondern einfach nur das Event emitten.
Du hast ja den Index in der Elternkomponente, somit machst du den Tag flexibler.

```vue
<tag
  v-for="(tag, index) in tags"
  :key="tag.title"
  :title="tag.title"
   :select-type="tag.selectType"
  @remove-tag="handleRemoveTag(index)"
/>
```

2021-08-17 08:03 UTC, merged